name: test
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
      - name: Format with Black
        run: black .
      - name: Lint with Ruff
        run: ruff .

  py_3x:
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [ '3.8', '3.9', '3.10', '3.11', '3.x']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        # https://github.com/actions/checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        # https://github.com/actions/setup-python
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
          cache: pip
      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -e '.[ci]'
          pip freeze
      - name: Setup test suite
        run: tox -vv --notest
      - name: Run test suite
        run: tox --skip-pkg-install
